### ISSUE TITLE
Confusing Similarity to three.proton

### ISSUE THREAD

**Issue by BlueMagnificent** [creativelifeform/three-nebula#55]
There seems to be an astonishing similarity between this project and [three.proton](https://github.com/a-jie/three.proton), even some of the examples are the same.

I'd like to know if they are related

**Comment by rohan-deshpande** [comment]
Yep this was originally a fork, but I changed the API quite a bit (with even more drastic changes planned) and am currently developing a fully featured particle system designer called **Nebula** for which `three-nebula` will be the engine. You can see a quick preview of the designer [here](https://www.youtube.com/watch?v=N-Dgf9YK9t0)

**Comment by wmcmurray** [comment]
@rohan-deshpande I strongly believe this should be stated somewhere (in the readme for example). Otherwise there is no proper way of knowing that the original code is from `three.proton` since you did not use Github's fork mechanism (beside comparing the two codebase, or going back to the [1st commit](https://github.com/creativelifeform/three-nebula/tree/d6ab63229066a7035afc1f4c9c17dfe018cae71c)).

To me, this looks like appropriating someone else's work and calling it your own. And well, that's not particularly cool.

**Comment by rohan-deshpande** [comment]
@wmcmurray https://github.com/creativelifeform/three-nebula/blob/master/LICENSE.md
