### ISSUE TITLE
Sprite Rotation

### ISSUE THREAD

**Issue by FlorentMasson** [creativelifeform/three-nebula#64]
Is there any way to initialize and/or animate Sprite rotation?
Looks like the only way is changing the material.rotation property and Nebula.Rotate is changing the Sprite rotation which has no effect with three.js

**Comment by rohan-deshpande** [comment]
Thanks for this - so basically you want the sprites themselves to rotate while the system is animating? We might need a new behaviour for that, probably something like `RotateMaterial`. Right now the rotation mutators relate to the particle / particle system itself, not the underlying materials.

This is definitely something I'd like to add, it shouldn't be too hard either. Feel free to submit a PR if you like but if not I will get to it soon.

**Comment by HardlineStudios** [comment]
Ha yeah I just spent the last hour trying to get individual sprites to rotate with no success. That would be a great option to an already great particle system!

**Comment by rohan-deshpande** [comment]
I've had to take a break from this and my upcoming particle designer GUI due to all the craziness happening in the world right now but I will be back on it _very_ soon. Watch this space, and thanks for using the library!

**Comment by rohan-deshpande** [comment]
Okay so here's an update on this, if you're not aware, I [launched the designer](https://getnebula.app), but I still haven't fixed this issue. 

Since the `GPURenderer` is now the preferred option for sprite/texture based systems, we need to add support in there. Most likely this will mean mapping the `particle.rotation` property into the vertex shader. 

Will most likely be working on this very soon and it will find its way into the editor not long after that. Sorry for the delay.

**Comment by daniels-gp** [comment]
any update on  particle.rotation ?

**Comment by andrewleek-droplab** [comment]
I have just made a PR regarding this here: https://github.com/creativelifeform/three-nebula/pull/210

Hopefully it correctly addresses the issue, I made a sandbox test to visualize it.

@rohan-deshpande  Thanks for all the work on this library!
